### ISSUE TITLE
Action links displayed in Month, Week and Day views in admin are not relevent for trashed events

### ISSUE THREAD

**Issue by benoitchantre** [sugarcalendar/core#119]
When an event is trashed, you can see it in the admin and a trash button is displayed.

The actions links displayed are _edit_ and _view_ instead of _restore_ or _delete permanently_ as in the list view.

**Comment by JJJ** [comment]
Hey @benoitchantre thanks for opening this issue here!

I believe we've fixed this in the most recent versions of Sugar Calendar. If you have trashed Events from previous versions, they'll need to be restored & re-trashed, or simply deleted.

## Day
<img width="1061" alt="jjj-sc-2020-09-29 at 13 52 13@2x" src="https://user-images.githubusercontent.com/88951/94602832-025f1f80-025b-11eb-9395-09cf4d466508.png">

## Week
<img width="1063" alt="jjj-sc-2020-09-29 at 13 53 01@2x" src="https://user-images.githubusercontent.com/88951/94602922-23c00b80-025b-11eb-87e0-eb70fb2d8480.png">

## Month
<img width="1051" alt="jjj-sc-2020-09-29 at 13 53 45@2x" src="https://user-images.githubusercontent.com/88951/94602965-38040880-025b-11eb-834f-f208781de665.png">

## List
<img width="1058" alt="jjj-sc-2020-09-29 at 13 54 09@2x" src="https://user-images.githubusercontent.com/88951/94603006-46522480-025b-11eb-92a8-76a3b75e500b.png">

Thoughts?

**Comment by JJJ** [comment]
This was addressed in the 2.0 branch, so closing this issue out.
