### ISSUE TITLE
Add calendar class to event "block"

### ISSUE THREAD

**Issue by shaynesanderson** [sugarcalendar/core#174]
When displaying events in calendar view, add a class that represents the calendar class to the entire "block" so that it could be styled according to what calendar it's part of. 

Example - this event is in the "Home" calendar so it's class would be "home" and could be styled separately from other events.

![Screenshot_2021-02-16 Calendar – SC TEST(1)](https://user-images.githubusercontent.com/1680163/108076584-3633b980-7031-11eb-8f0c-9ae7b706f764.png)

**Comment by JJJ** [comment]
This one might be tough to do on the theme-side calendar.

It's only because the Calendar and the Events in the day are happening in the same loop, so the table-cell for the day doesn't really know what's going to be inside it until it's too late.

In the admin-area calendars, I do some pre-processing of Events that would allow for this, and that could make its way to the theme-side someday.

I think this issue will probably end up dormant for a while, until we make output blocks, and decide we want to update all of it.

**Comment by shaynesanderson** [comment]
Understood!

**Comment by pippinsplugins** [comment]
This is something that's been requested for years, as far back as I can remember.

@JJJ what about a kind shitty JS work around? Could loop through the events on render and then inject the class name(s). Not amazing but would probably work okayish

**Comment by JJJ** [comment]
@pippinsplugins that is doable, and would work okayish. 🤣

We'd want to be pretty confident with the classes we add, so that the janky way now matches what a hypothetical best way will be later. If we get it wrong early, we'd break sites by changing them in the future.

* Is `{$taxonomy}-{$term_slug}` adequate?
* Is this maybe add-on territory at first?

**Comment by pippinsplugins** [comment]
I don't know that I'd suggest it being an add-on unless it goes further and provides color controls for each block and perhaps more.

How about putting the cell classes into Standard and then consider building an add-on that utilizes those classes sometime in the future?

**Comment by JJJ** [comment]
> How about putting the cell classes into Standard and then consider building an add-on that utilizes those classes sometime in the future?

We could do it that way pretty easily, with an inline script in a dedicated file hooked to `admin_head` or similar.

**Comment by JJJ** [comment]
## Settings > Display

![jjj-on-2021-03-12-at-12-21-55@2x](https://user-images.githubusercontent.com/88951/110982164-d1b50300-832d-11eb-800f-f67f2485a5ed.png)

## Each
This value will style each Event based on its own Calendar Color.

<img width="595" alt="jjj-on-2021-03-12-at-12-24-31@2x" src="https://user-images.githubusercontent.com/88951/110982379-1345ae00-832e-11eb-8707-56f9726937b2.png">

## First
This value will style each table cell based on the first Event in that day.

<img width="612" alt="jjj-on-2021-03-12-at-12-26-11@2x" src="https://user-images.githubusercontent.com/88951/110982464-26f11480-832e-11eb-8473-a9d5e2a1c9c0.png">

## Blend
This value will style each table cell based on the average color of all Events in that day.

<img width="603" alt="jjj-on-2021-03-12-at-12-26-44@2x" src="https://user-images.githubusercontent.com/88951/110982583-50aa3b80-832e-11eb-8574-654797224deb.png">

**Comment by pippinsplugins** [comment]
This is _really_ great!

@pderksen pinging you for your eyes as we'll definitely want to do a blog post as this when it's released. It's been a highly requested feature.

**Comment by JJJ** [comment]
@pderksen and I will work on the release post together privately.

One us will circle back and post a link to it here when it goes live.

Thanks @pippinsplugins and @shaynesanderson for testing & review. 🤜🤛
